name: travel_olimp
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/bgacc.jpg
    - assets/images/ava.jpg
    - assets/images/bgchat.jpg
    - assets/images/almaz.jpg
    - assets/images/gorodFirst.jpg
    - assets/images/mauntens.jpg
    - assets/images/chat.jpg
    - assets/images/favorite.jpg
    - assets/images/filters.jpg
    - assets/images/history.jpg
    - assets/images/previewLogo.jpg

    - assets/icons/logo.jpg
    - assets/icons/